version: '3.8'

services:
  cassandra-container:
    container_name: cassandra-container
    image: cassandra:4.1
    environment:
      CASSANDRA_CLUSTER_NAME: ${CASSANDRA_CLUSTER_NAME}
      CASSANDRA_DC: ${CASSANDRA_DC}
      CASSANDRA_RACK: ${CASSANDRA_RACK}
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_PASSWORD_SEEDER: "true"
      CASSANDRA_USER: ${CASSANDRA_USER}
      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
    ports:
      - "${CASSANDRA_PORT}:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - cassandra
    restart: unless-stopped

networks:
  cassandra:
    driver: bridge

volumes:
  cassandra_data:
    driver: local
