version: '3.8'

services:
  mysql-container:
    container_name: mysql-container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql
    restart: unless-stopped

  phpmyadmin-container:
    container_name: phpmyadmin-container
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql-container
      PMA_PORT: 3306
      # Auto login
      PMA_USER: ${MYSQL_ROOT_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - mysql
    depends_on:
      - mysql-container
    restart: unless-stopped

networks:
  mysql:
    driver: bridge

volumes:
  mysql_data:
    driver: local
